### ISSUE TITLE
Add mime type application/pdf to application.yml

### ISSUE THREAD

**Issue by rlovtangen** [grails/grails-profile-repository#17]
I maintain the wkhtmltopdf plugin which generates PDF.
For it to work, the user need to add mime type `application/pdf` to property `grails.mime.types`:
```
 pdf: application/pdf
````
Since this is a quite standard mime type, is it possible to add it to the skeletons? Or is there a reason the current list includes some mime types but not others?

**Comment by graemerocher** [comment]
Sure, pull request welcome
