### ISSUE TITLE
Wrap templates with IIFE

### ISSUE THREAD

**Issue by dmahapatro** [grails/grails-profile-repository#38]
Minor improvement:

We can go one step ahead to stick to angular style guide by surrounding modules and components with IIFE to avoid contaminating global scope. For example:

```JavaScript
(function() {
    angular.module("${fullName}", [${dependencies.join(', ')}]);
})();
```

and for directives:

```JavaScript
(function(){
    angular
        .module("${moduleName}")
        .directive("${propertyName}", ${propertyName});

    function ${propertyName}() {
        var directive = {
            link: link,
            template: "",
            scope: {}
        };

        return directive;

        function link(scope, element, attrs) {

        }
    }
})();
```

**Comment by Schlogen** [comment]
@dmahapatro This is done automatically by the `com.craigburke:js-closure-wrap-asset-pipeline` plugin. Note the usage of `//= wrapped` at the top of the files. Take a look at the resulting file sent to the client.

**Comment by dmahapatro** [comment]
Thanks @Schlogen for the clarification, did check that before.
