### ISSUE TITLE
angular - make assets dir configurable

### ISSUE THREAD

**Issue by zyro23** [grails/grails-profile-repository#46]
currently, the angular profile and command assets are put/generated into `grails-app/assets/javascripts/...`.
i think it may be better to put them into `grails-app/assets/angular/...` (or similar top-level assets dir):
* when using the angular profile along with other javascript assets, it can get confusing which files/dirs in `javascripts` belong to the angular-part of an app and which files do not
* after all, it is not only javascript (`*.tpl.html`, etc.)

an `angular.assets.dir` (or similar..) config option (config.yml/build.gradle) would be great.

what do you think? thanks, zyro

**Comment by Schlogen** [comment]
@zyro23 Can you give me a use case?

The templates are designed to be stored alongside your controllers, etc `/grails-app/assets/javascripts/example/templates`.

Third party libraries should be brought in with bower and they get put in `grails-app/assets/bower`

**Comment by zyro23** [comment]
when integrating into an existing app where there is already infrastructure present and that app is exposing a classic web ui (with non-bower js) alongside an angular part (bower + angular js), it would be nice to have the angular part clearly separated inside the assets dir. but please do not consider this blocking or having high prio. more nice-to-have.

**Comment by Schlogen** [comment]
@zyro23 You could move the assets into an /angular folder. You would just need to remember to define that as the top level package when creating assets. Example `grails create-ng-controller angular.core.main` would create `/angular/core/controllers/mainController.js`. Does that work for you?

**Comment by zyro23** [comment]
@Schlogen but that would still reside inside `grails-app/assets/javascripts` (e.g. https://github.com/grails/grails-profile-repository/blob/master/profiles/angular/commands/create-ng-controller.groovy#L19), right?
i was looking for `grails-app/assets/myJsAppDirContainingHtmlTemplatesEtc`.

**Comment by Schlogen** [comment]
@zyro23 I see what you mean. I'll look into it

**Comment by Schlogen** [comment]
@zyro23 
Currently the path "src/test/javascripts" is being used to store test cases
In your use case should the change in path affect that as well?

**Comment by zyro23** [comment]
@Schlogen for the moment i am fine with `src/test/javascripts` because that makes a good fit into the dir structure in `src/test`. thank you!

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/a10035256699ffeaaf191bb5caa0586c83e0a06d
