### ISSUE TITLE
Rest-api profile: _error.gson autogenerated - compilation error

### ISSUE THREAD

**Issue by orkonano** [grails/grails-profile-repository#47]
I'm using profile rest-api and I've an error with the _error.gson generated.
When I try to POST a resource with status code 422 (An invalid field domain), I receive this exception
> Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
_info_app_name__errors__errors_gson: 10: [Static type checking] - Cannot find matching method grails.views.api.HttpView$Request#status(org.springframework.http.HttpStatus). Please check if the declared type is right and if the method exists.
@ line 10, column 1.
  page.status UNPROCESSABLE_ENTITY

Then I've changed this line 
> page.status UNPROCESSABLE_ENTITY

for this one 
> response.status UNPROCESSABLE_ENTITY

And worked fine.

**Comment by alvarosanchez** [comment]
Fixed by 4d2c70eb1939d3245eface5e63f98406fa8839fa
