### ISSUE TITLE
Angular profile - Default application not named correctly

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-profile-repository#52]
The default application is currently called "app". It should be named whatever the last "package" name of the application. Example:

`grails create-app test-demo -profile angular`

"app.js" should be named "demo.js"

**Comment by Schlogen** [comment]
@graemerocher Going about this by modifying the code generation scripts isn't very feasible from my initial look. Is it possible to get that information from the `@grails.codegen...`. If not, can you point me in the right direction so I can add it?

**Comment by graemerocher** [comment]
In your example above the package name would be `test.demo`, not `demo` so that would result in a `test.demo.js` file. I assume that is what you want. Does renaming `app.js` to `@grails.codegen.defaultPackage@.js` not work for you?

**Comment by Schlogen** [comment]
@graemerocher I would actually prefer just a `demo.js` file. Some things can be reworked to allow for a `test.demo.js` file, however I would consider that plan B. If you don't see any easy path forward to have just a `demo.js` file created, let me know and I'll have to do some codegen changes as all of the scripts expect a `demo.js` file.

**Comment by graemerocher** [comment]
There is no easy way to do that right now no, we should probably add some customisable hook for profiles that can run some arbitrary script when `create-app` is executed for special cases like this

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/d01fb5df6df85e1ea0b7ecffe583d658b7c28b4b
