### ISSUE TITLE
issue with angular-bootstrap (uib) and contextPath

### ISSUE THREAD

**Issue by dularion** [grails/grails-profile-repository#64]
When using the angular ui-bootstrap library together with an app that has a context path other than "/", for example "/myApp/", then the interceptor in the core app adds the context path to the uib template URLs and breaks the app. A quickfix is adding uib/ in the if-statement and thereby excluding those libraries, but I think this case shows that the entire interceptor should be reconsidered.

**Comment by whatevercode** [comment]
+1

**Comment by Schlogen** [comment]
Can you post an example that demonstrates the problem?

**Comment by dularion** [comment]
for example, ui-bootstrap adds the following to template cache: 

```
  $templateCache.put("uib/template/rating/rating.html",
    "<span ng-mouseleave=\"reset()\" ng-keydown=\"onKeydown($event)\" tabindex=\"0\" role=\"slider\" aria-valuemin=\"0\" aria-valuemax=\"{{range.length}}\" aria-valuenow=\"{{value}}\">\n" +
    "    <span ng-repeat-start=\"r in range track by $index\" class=\"sr-only\">({{ $index < value ? '*' : ' ' }})</span>\n" +
    "    <i ng-repeat-end ng-mouseenter=\"enter($index + 1)\" ng-click=\"rate($index + 1)\" class=\"glyphicon\" ng-class=\"$index < value && (r.stateOn || 'glyphicon-star') || (r.stateOff || 'glyphicon-star-empty')\" ng-attr-title=\"{{r.title}}\" aria-valuetext=\"{{r.title}}\"></i>\n" +
    "</span>\n" +
    "");
```

and then this is intercepted by the angular core module (https://github.com/grails/grails-profile-repository/blob/master/profiles/angular/skeleton/grails-app/assets/javascripts/%40grails.codegen.defaultPackage.path%40/core/%40grails.codegen.defaultPackage%40.core.js) and rewritten with `contextPath + "/" + config.url;` and becomes faulty.

**Comment by dularion** [comment]
the before mentioned quickfix is this: 
```
if (!config.url.indexOf("/") == 0 && contextPath && config.url.indexOf("uib/template") == -1) {
   config.url = contextPath + "/" + config.url;
}
```

**Comment by Schlogen** [comment]
OK, I understand the issue. So you said 
>  I think this case shows that the entire interceptor should be reconsidered

Any suggestions are welcome. You can post an implementation here for discussion. Note that for the profile it can't be assumed the user is using ui-bootstrap.

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-profile-repository/pull/79
