### ISSUE TITLE
Clean app with AngularJS profile: ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by tvinke** [grails/grails-profile-repository#65]
After having created a clean application with the AngularJS profile e.g.

`grails create-app angular --profile=angular`

and starting my newly created app, the index page loads on http://localhost:8080 but contains JavaScript errors, such as

```
TypeError: angular is undefined
 angular-resource.js:8:5
ReferenceError: angular is not defined
 angular.core.js:9:1
ReferenceError: angular is not defined
 DomainServiceFactory.js:10:1
ReferenceError: angular is not defined
 angular.index.js:11:1
ReferenceError: angular is not defined
 applicationDataFactory.js:5:1
ReferenceError: angular is not defined
 indexController.js:5:1
ReferenceError: angular is not defined
 ui-bootstrap-tpls.js:7:4
ReferenceError: angular is not defined
 angular.js:8:1
```

Screenshot: https://www.dropbox.com/s/lpsnnhqlik1h0ch/grails%20314%20ReferenceError%20angular%20is%20not%20defined.png?dl=0

Grails 3.1.4 either on Chrome/Windows 7 (using Git Bash) or on Firefox/Linux Mint using sdkman.

Couldn't find any existing issues or wasn't able to relate any of the existing ones to this problem. But I don't think out of the box these JS errors should happen, or am I missing some steps?

**Comment by Schlogen** [comment]
@tvinke Can you upload an example that reproduces the problem?

**Comment by djse1993** [comment]
You need to install bower in order to make Grails recognize Angular. 
![image](https://cloud.githubusercontent.com/assets/8876392/15130213/a398af02-1614-11e6-8fa3-693efe5baeac.png)

**Comment by tvinke** [comment]
Hi dsje1933, is this really true? I assumed it would work right out of the box with all dependencies already present and no need to install any 3rd party tools?

Schlogen, I will upload an example as soon as I can - but it will be nothing more than the empty, skeleton application created by the aforementioned parameters.

**Comment by Schlogen** [comment]
Closing this issue as no feedback provided
