### ISSUE TITLE
Skipping karma tests ?

### ISSUE THREAD

**Issue by walshe** [grails/grails-profile-repository#66]
I am using the grails 3 angular profile, how can I skip the karma tests when I execute grails test-app ?

**Comment by Schlogen** [comment]
Are you certain they are getting executed with `grails test-app`? The last I knew that was not the case

**Comment by walshe** [comment]
yes

grails> test-app -unit SearchController
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:instrument SKIPPED
:copyCoberturaDatafile SKIPPED
:bowerInit UP-TO-DATE
:nodeSetup UP-TO-DATE
:bowerDependencies UP-TO-DATE
:bowerConfig
:bowerComponents UP-TO-DATE
:bowerInstall UP-TO-DATE
:karmaInit UP-TO-DATE
:karmaDependencies UP-TO-DATE
:karmaGenerateConfig UP-TO-DATE
:karmaRun
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 9 of 9 SUCCESS (0.007 secs / 0.041 secs)
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResource

**Comment by Schlogen** [comment]
The task dependency is set in the `karma-gradle` plugin here: https://github.com/craigburke/karma-gradle/blob/master/src/main/groovy/com/craigburke/gradle/KarmaPlugin.groovy#L136

https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html

You can use the `-x` option to skip `karmaRun`

**Comment by walshe** [comment]
thanks, any idea how I can run a single karma test too?

**Comment by Schlogen** [comment]
If you are using Jasmine, this is 1 option: http://stackoverflow.com/a/23793631/1264846. I don't believe the karma gradle plugin supports command line parameters, however that would be an issue for that plugin: https://github.com/craigburke/karma-gradle
