### ISSUE TITLE
html files excluded by asset pipeline

### ISSUE THREAD

**Issue by walshe** [grails/grails-profile-repository#69]
I am using grail 3.1.3 qith the angularjs profile, all goo so far except when i tried to configure proper angular html templates 

The asset pipeline plugin which is pre-included seems to be passing over any html files e.g. in my "<module>/templates" folder and not including them in the sources that get used by the app

//= wrapped

//= require /uk/ac/xxx/coursefinder/core/uk.ac.xxx.coursefinder.core
//= require routes

//= require_self
//= require_tree services
//= require_tree controllers
**//= require_tree templates**

angular.module("uk.ac.xxx.coursefinder.courseguide", [
    "ngRoute",
    "uk.ac.xxx.coursefinder.core"
]).config(function($routeProvider) {
    $routeProvider.when('/', {
        templateUrl: "templates/list.html",
        controller:  "controllers/CourseGuideController as ctrl"
    })

        .otherwise({redirectTo: '/'});

});

the funny thing is, if I add a .js file inside the templates folder it does seem to get included.

do I need to specifically configure it to include .html files some place ?

**Comment by Schlogen** [comment]
Check out the documentation on using that plugin: https://github.com/craigburke/angular-template-asset-pipeline. Looks like the filename is incorrect, as well as the URL you are using to attempt to retrieve it.

**Comment by walshe** [comment]
ok, thanks, I didnt realise the naming convention i.e. the *.tpl* in the path and the fact that one has to leave out */templates/* from the path.  My app is running now and assigning template and controller to the correct angular path, however now my karma/angular tests are failing with strange messages:

:karmaRun
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: [$injector:nomod] Module 'uk.ac.xxx.coursefinder.courseguide' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
  http://errors.angularjs.org/1.4.10/$injector/nomod?p0=uk.ac.xxx.coursefinder.courseguide
  at /Developer/dev/xxx/coursefinder-grails-angular/grails-app/assets/bower/angular/angular.js:2014


wondering of it has to do with the $templateCache magic done by the asset pipeline stuff

**Comment by Schlogen** [comment]
I would seriously doubt that would have any affect. You're certain this worked prior to the change?

**Comment by walshe** [comment]
yeah, before this I only had a gsp with the html all in thereand where controller was assigned with the ng-controller=xxx attribute on the div.  However after I switched to proper  html templayting with **.config(function($routeProvider)...when('/', {...** etc , then the tests started to fail

**Comment by Schlogen** [comment]
Please create a separate issue and include an example project so we can investigate

**Comment by walshe** [comment]
things started passing again after I moved the routes from their own file (routes.js) into the main module file like so:

//= wrapped


//= require_self

//= require /uk/ac/lse/coursefinder/core/uk.ac.xxx.coursefinder.core

//= require_tree services
//= require_tree controllers
//= require_tree templates

angular.module("uk.ac.xxx.coursefinder.courseguide", [
    "ngRoute",
    "uk.ac.lse.coursefinder.core"
]).config(function($routeProvider) {
    $routeProvider.
        when('/', {
            templateUrl: "/uk/ac/xxx/coursefinder/courseguide/list.html",
            controller:  "CourseGuideController as ctrl"
        })
});
