### ISSUE TITLE
Geb UI tests

### ISSUE THREAD

**Issue by walshe** [grails/grails-profile-repository#76]
Any chance of some Geb tests that drive the actual angular UI, having a woeful time here trying to assert anything other than the windows title, I guess its because of timing issues and dynamically loaded content by angular into the dom.  

Even a simple example would be great

**Comment by graemerocher** [comment]
Wouldn't it be better to write these tests in JavaScript?

**Comment by walshe** [comment]
Im relatively new to the angularjs profile.

So far Ive written some jasmine tests to test angular controllers and angular services with collaborators mocked out. Is it possible to write jasmine tests to run full stack end to end functional tests too ?

**Comment by Schlogen** [comment]
You can write jasmine tests for end to end. That would require you to use [protractor](http://angular.github.io/protractor/#/) and would have nothing to do with Grails itself.
