### ISSUE TITLE
Enhance plugin profile to provide scaffolded documentation setup

### ISSUE THREAD

**Issue by robertoschwald** [grails/grails-profile-repository#84]
It might be a good idea to enhance the plugin profile to create documentation stubs, to make it easier for plugin developers to create plugin documentation, and to have the same ci / layout across plugin documentation

Idea is to create on "grails create-plugin" by default:
 - README.md 
 - AsciiDoc configuration in build.gradle
 - Stub documentation in src/docs based on templates

**Comment by Schlogen** [comment]
The profiles have been split out to the `grails-profiles` account. Please post this issue here: https://github.com/grails-profiles/plugin

**Comment by robertoschwald** [comment]
thanks.
